### PR TITLE
Reduce fleetshard-sync log verbosity

### PR DESCRIPTION
**Pull request by SimonBaeumer**
## Description
This pull request reduces the log verbosity. As it's helpful to debug the system then terminals and not being flooded by log messages with no debugging value.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

 - CI

### CODE REVIEW

**Review by kovayur — APPROVED** [review]
Nice, this will indeed increase logs readability

**Review by kovayur — APPROVED** [review]
LGTM

**Comment by mtesseract** [comment]
[Failure in CI](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_acs-fleet-manager/419/pull-ci-stackrox-acs-fleet-manager-main-e2e/1571905279249879040) seems to be:

```
Central
/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:53
  should be created and deployed to k8s
  /go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:82
    [It] should create AWS Route53 records
    /go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:164
  Begin Captured GinkgoWriter Output >>
    AUTH_TYPE="STATIC_TOKEN"
    FLEET_MANAGER_ENDPOINT="http://localhost:8000/"
  << End Captured GinkgoWriter Output
  Unexpected error:
      <*errors.errorString | 0xc0012a6e90>: {
          s: "unable to find admitted ingress. route: rhacs-ccka19n28qj05lmeuv3g/managed-central-reencrypt",
      }
      unable to find admitted ingress. route: rhacs-ccka19n28qj05lmeuv3g/managed-central-reencrypt
  occurred
  In [It] at: /go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:171
  Full Stack Trace
    github.com/stackrox/acs-fleet-manager/e2e.glob..func4.2.6()
    	/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:171 +0x1c3
```

Does this ring a bell, @kovayur @johannes94?

**Pull request merged**
