### PR TITLE
ROX-16664: add KeyGenerator interface and implementations

### PR DESCRIPTION
**Pull request by johannes94**
## Description
This PR adds a `KeyGenerator` interface and respective `AES256KeyGenerator` and `KMSDataKeyGenerator` implementations of the interface.

This implementations will later be used to generate a encryption key to provide to a managed central tenant in order to encrypt secrets stored in its DB.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

CI and local unit tests are sufficient.

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

### CODE REVIEW

**Comment by ludydoo** [comment]
Do we need to generate the keys? I thought KMS could be used to encrypt/decrypt directly, without us ever having access to key material

**Comment by johannes94** [comment]
> Do we need to generate the keys? I thought KMS could be used to encrypt/decrypt directly, without us ever having access to key material
@ludydoo 

There are two reasons for that.

1. Central will not implement a KMS integration for now

- The "central" component itself has no strict dependency to AWS like we have for our cloud service, so core workflows decided to not implement KMS integration for this feature because specifying a key is a more general implementation that all customers could potentially use. The interface for us to use will only be specifying a AES256 key in a K8s secret. That's why we need the key material in this case.

2. KMS API encryption/decryption is limited to 4KB. 

I learned this during the secret encryption I've implemented for secret backups. In case you need to encrypt more than that you have to generate a data key and implement encryption in your own application. https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#data-keys. In this case central-ca was to big to be encrypted via API, so we had to go the data key route.

For notifiers we would have the same issue because sometimes the credentials for notifiers can be certificates.

**Comment by ludydoo** [comment]
Also interesting: https://github.com/hashicorp/go-kms-wrapping

**Comment by johannes94** [comment]
> BTW, is [ROX-16663](https://issues.redhat.com//browse/ROX-16663) the right jira ticket? (from the title) I'm trying to get more context on the encryption feature.

You're right the actual ticket is [ROX-16664](https://issues.redhat.com/browse/ROX-16664). 

> For 2, it would be possible to use envelope encryption instead of sending the whole block to KMS. https://docs.aws.amazon.com/wellarchitected/latest/financial-services-industry-lens/use-envelope-encryption-with-customer-master-keys.html

IIUC this is essentially what is implemented in the secret backup feature.

Encryption:
1. Generate a data key
2. Encrypt data key with KMS key, encrypted payload with data key
3. Store encrypted data key with encrypted payload

Decryption:
1. Get encrypted data key and encrypted payload
2. Decrypt data key with KMS key
3. Decrypt payload with data key

**Review by vladbologa — APPROVED** [review]
LGTM

**Pull request merged**
