### PR TITLE
fix e2e admin tests by reducing required resources

### PR DESCRIPTION
**Pull request by johannes94**
## Description
The e2e admin tests fail because they set resource requests and limits for central to values that did not allow central pods to be created properly. This PR adjusts those resources so that they are close to the default values used in the "non-admin" tests. With this the test should work again.

## Checklist (Definition of Done)

- ~~[ ] Unit and integration tests added~~
- ~~[ ] Added test description under `Test manual`~~
- ~~[ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- [ ] CI and all relevant tests are passing
- ~~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~~
- ~~[ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
- ~~[ ] Add secret to app-interface Vault or Secrets Manager if necessary~~

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

### CODE REVIEW

**Comment by johannes94** [comment]
> Was it just CPU that was causing issues? Because it looks like memory requests were actually increased.

True, I mixed something up here. I put values that are basically the `defaultValue + 10`. I was unsure what is causing it because we're missing meaningful logs. I'll undo the changes for memory.

**Comment by kylape** [comment]
Do you know if the cpu limits need to be reduced?  I worry a bit that CI tests would take longer since the CPU limits will be lowered, but I'm not familiar with the details around the issues.

**Comment by johannes94** [comment]
> Do you know if the cpu limits need to be reduced? I worry a bit that CI tests would take longer since the CPU limits will be lowered, but I'm not familiar with the details around the CI issues.

Perhaps we could also increase the resources we require in the openshift-ci config. I don't think that reducing the limit in this test will have a big impact on time required for an e2e tests. It's just the resources for the central/scanner pods. In this test they are basically created and deleted nothing more happens. So having lower CPU limits shouldn't be a problem because there's no processing happening in this pods.

**Review by kylape — APPROVED** [review]

**Comment by johannes94** [comment]
@kylape failing CI showed that actually the memory requests were to low and not the cpu requests to high (or maybe both). I think the initial approach with getting all values very similar to what the "default" values are worked fine so I reverted the "revert" of the memory changes.

**Pull request merged**
