### PR TITLE
Add dinosaur counter badge to README.md

### PR DESCRIPTION
**Pull request by kovayur**
## Description
This PR adds the following badge to README.md: Dinosaur counter

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

### CODE REVIEW

**Review by SimonBaeumer — APPROVED** [review]
YEAAAAH! 🦖 
Wanna share that with the Kafka team in Zulip?

**Review by vladbologa — APPROVED** [review]
Would it make sense to explain why we are counting this?

**Review by johannes94 — APPROVED** [review]
👍

**Comment by kovayur** [comment]
> Would it make sense to explain why we are counting this?

Clarifying comment added.

**Comment by kovayur** [comment]
> Wanna share that with the Kafka team in Zulip?
@SimonBaeumer done 🙌

**Pull request merged**
