### PR TITLE
ROX-11309: Make liveness probe based on /api

### PR DESCRIPTION
**Pull request by kurlov**
## Description

Return liveness probe back to /api based

### CODE REVIEW

**Review by porridge — APPROVED** [review]

**Comment by mtesseract** [comment]
Hi @kurlov, do you know what the state of this PR is? Should we rebase and re-review?

**Comment by mtesseract** [comment]
Can this be closed @kurlov ?

**Comment by porridge** [comment]
I don't think anyone ever did an in-depth analysis of what is the right approach here.
Although apparent lack of related problems so far hints that this indeed might be unnecessary.

**Comment by kurlov** [comment]
I think it might make sense to have an /api based liveness probe. App might not be ready to serve traffic due to long migration or not yet connected to DB and in this case /api probe should fail

**Pull request closed without merging**
