### PR TITLE
ROX-12462: add env to fleetshard-sync, probe, cloudwatch-exporter

### PR DESCRIPTION
**Pull request by stehessel**
## Description
Follow up to #822 to make sure fleetshard-sync, probe and cloudwatch exporter metrics are also labelled in the same way as Central/Scanner metrics.

## Checklist (Definition of Done)

- [ ] ~Unit and integration tests added~
- [ ] ~Added test description under `Test manual`~
- [ ] ~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~
- [x] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

### CODE REVIEW

**Comment by stehessel** [comment]
\retest

**Review by dhaus67 — APPROVED** [review]

**Comment by stehessel** [comment]
\retest

**Pull request merged**
