### PR TITLE
Set ACS Operator CPU request and limit to 2

### PR DESCRIPTION
**Pull request by ebensh**
## Description
Set explicit ACS Operator CPU request and limit to 2 (via OLM config).

## Checklist (Definition of Done)
- ~~[ ] Unit and integration tests added~~
- ~~[ ] Added test description under `Test manual`~~
- ~~[ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~~
- ~~[ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~

## Test manual

Will test in stage using CD to ensure the config is okay, then push to prod to see if it addresses the issue.

### CODE REVIEW

**Review by porridge — APPROVED** [review]
I dream of a ticket that we could link to from PR description that would provide the rationale...

**Review by vladbologa — COMMENTED** [review]
The deployment managed by the operator has 2 containers, each with its own resource settings:
- manager (the actual operator)
- kube-rbac-proxy

I wonder what exactly this config will change. Hopefully just the manager, but I'm not sure.

**Review by vladbologa — APPROVED** [review]

**Comment by stehessel** [comment]
Why did you set the request equal to the limit? Isn't increasing the limit enough to avoid throttling?

**Comment by porridge** [comment]
> Why did you set the request equal to the limit? Isn't increasing the limit enough to avoid throttling?

Only if the node has enough resources, I think. Setting the request helps bin packing make sure it does.

**Comment by stehessel** [comment]
> Only if the node has enough resources, I think. Setting the request helps bin packing make sure it does.

Won't a high request just lead to the pod being unscheduled if not enough resources are available - i.e. what seemed to have happened here? Maybe we should assign a higher pod priority to the operator pod to make sure it gets scheduled.

**Comment by porridge** [comment]
> > Only if the node has enough resources, I think. Setting the request helps bin packing make sure it does.
> 
> Won't a high request just lead to the pod being unscheduled

Yes, this is a risk, but I definitely would not use the word "just" :-)
It might be a good compromise if we're reasonably sure CPU spikes will not be coordinated across multiple pods (which is not obvious). However I think unschedulability issues could mean that using smaller `requests` would provide a false sense of security in case of a resource crunch. 

> Maybe we should assign a higher pod priority to the operator pod to make sure it gets scheduled.

I'm not sure we want to preempt other control plane components :thinking:

**Pull request merged**
