### PR TITLE
added cluster config for local CRC

### PR DESCRIPTION
**Pull request by johannes94**
## Description
Added cluster config for Code Ready Containers (CRC)

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

### CODE REVIEW

**Comment by kovayur** [comment]
WDYT about merging all kinds of local clusters into a single file?

**Review by SimonBaeumer — APPROVED** [review]

**Comment by johannes94** [comment]
> WDYT about merging all kinds of local clusters into a single file?

Do you mean putting them all into one file and commenting the configs you are not using? I like the way it is currently working, cause you can specify which file to use when running fleet-manager without changing something in the files.

**Comment by kovayur** [comment]
> Do you mean putting them all into one file and commenting the configs you are not using? I like the way it is currently working, cause you can specify which file to use when running fleet-manager without changing something in the files.
I mean that we can leave multiple clusters with different IDs and names for each cluster type (without commenting). Then we don't need to change something in the files either. Moreover we can switch, say, from `colima` to `crc` without restarting the fleet manager

**Comment by johannes94** [comment]
Good idea @kovayur. I tried to test and run into the problem that fleet-manager crashes if a given cluster in the config is not found in the current kubeconfig you're running fleet-manager with. Looks to me like that would only work if one would have all supported cluster types in his kubeconfig. Is it OK if I merge, and we revisit another time?

**Comment by kovayur** [comment]
Sure, no objections @johannes94. Thanks for checking.

**Pull request merged**
