### PR TITLE
Run pre-commit hooks in github actions.

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

Using the [pre-commit action](https://github.com/pre-commit/action), this will run all hooks configured within `.pre-commit.config.yaml` within GitHub actions.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* main
  * **PR #193** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/193" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/193?utm_source=stack-comment).

**Comment by dhaus67** [comment]
@mtesseract not sure we want this in github, would be also OK to me to port this to openshift CI in case we only want to have the job definitions there.

**Comment by mtesseract** [comment]
I don't have concerns regarding having certain pipeline steps (e.g. linting) also in GitHub.
Were you able to test this already?

**Comment by dhaus67** [comment]
@mtesseract Yeah, see CI runs on this branch.

**Review by mtesseract — APPROVED** [review]

**Pull request merged**
